CONFIG = {
    "wifi_ssid": "NOME_DA_REDE",
    "wifi_password": "SENHA_DA_REDE",
    "api_url": "http://IP_DO_BACKEND:8000/leituras",
    "api_key": "",
    "device_id": "esp32-sensores-01",
    "send_interval_ms": 3000,
    "moisture_dry_adc": 4095,
    "moisture_wet_adc": 1500,
    "moisture_wet_threshold": 3400,
    "moisture_digital_active_low": True,
    "moisture_use_digital_wet": False,
    "vibration_active_high": False,
    "vibration_sample_count": 25,
    "vibration_event_samples": 0,
    "vibration_sample_delay_ms": 4,
    "vibration_edge_threshold": 4,
    "vibration_continuous_windows": 2,
    "acceleration_attention_threshold_g": 0.4,
    "acceleration_alert_threshold_g": 0.7,
    "buzzer_active_high": True,
    "buzzer_pulse_moisture_min_threshold": 2400,
    "buzzer_continuous_moisture_threshold": 3400,
    "buzzer_normal_pulse_ms": 80,
    "buzzer_normal_interval_ms": 5000,
}
